Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using Prello.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Prello.Controllers
{
    public class ClientsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ClientsController(ApplicationDbContext db)
        {
            _db = db;
        }

        // GET: Clients
        public IActionResult Index()
        {
            return View(_db.Clients.ToList());
        }

        // GET: Clients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Name,Email")] Client client)
        {
            if (ModelState.IsValid)
            {
                _db.Add(client);
                _db.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Client/Edit/id
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = _db.Clients.FirstOrDefault(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }

        // POST: Client/Edit/id
        [HttpPost]
        public IActionResult Edit(int id, [Bind("Id,Name,Email")] Client client)
        {
            if (ModelState.IsValid)
            {
                if (id != client.Id)
                {
                    return NotFound();
                }
                else
                {
                    _db.Update(client);
                    _db.SaveChanges();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Delete/id
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = _db.Clients.FirstOrDefault(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Clients/Delete/id
        [HttpPost]
        public IActionResult Delete(int id, bool notUsed)
        {
            var client = _db.Clients.FirstOrDefault(m => m.Id == id);
            _db.Clients.Remove(client);
            _db.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        // Get: Search Client
        public IActionResult Search(string searchString)
        {
            if (searchString == null)
            {
                return View("NotFoundData");
            }

            var client = _db.Clients.Where(m => m.Name == searchString).ToList();

            if (client == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(client);
        }
    }
}

Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;
using Prello.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Prello.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ProjectsController(ApplicationDbContext db)
        {
            _db = db;
        }

        // GET: Projects
        public IActionResult Index()
        {

            return View(_db.Projects.ToList());
        }

        // GET: Projects/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Name,Description,Status,DueDate")] Project project)
        {
            if (ModelState.IsValid)
            {
                _db.Add(project);
                _db.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Project/Edit/id
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = _db.Projects.FirstOrDefault(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }
            return View(project);
        }

        // POST: Projects/Edit/id
        [HttpPost]
        public IActionResult Edit(int id, [Bind("Id,Name,Description,Status, DueDate")] Project project)
        {
            if (ModelState.IsValid)
            {
                if (id != project.Id)
                {
                    return NotFound();
                }
                else
                {
                    _db.Update(project);
                    _db.SaveChanges();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Delete/id
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = _db.Projects.FirstOrDefault(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Projects/Delete/id
        [HttpPost]
        public IActionResult Delete(int id, bool notUsed)
        {
            var project = _db.Projects.FirstOrDefault(m => m.Id == id);
            _db.Projects.Remove(project);
            _db.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        // Get: Search Project
        public IActionResult Search(string searchString)
        {
            if (searchString == null)
            {
                return View("NotFoundData");
            }

            var project = _db.Projects.Where(m => m.Name == searchString).ToList();

            if (project == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(project);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Prello</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-color border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Prello</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Projects" asp-action="Index">Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Clients" asp-action="Index">Clients</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Prello 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>